name: Standard Change Proposal (SCP)
description: Propose a change to the WEKAOU specification
title: "[SCP] "
labels: ["status: proposed", "type: scp"]
body:
  - type: markdown
    attributes:
      value: |
        ## Standard Change Proposal
        
        Use this template to propose changes to the WEKAOU specification.
        
        **Before submitting**: Search existing issues to avoid duplicates.
        
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One-paragraph overview of the proposed change
      placeholder: "This RFC proposes to..."
    validations:
      required: true
      
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this change needed? What problem does it solve?
      placeholder: |
        Current state:
        Problem:
        Benefits:
    validations:
      required: true
      
  - type: textarea
    id: detailed-design
    attributes:
      label: Detailed Design
      description: How will this work? Include examples, pseudocode, or diagrams.
      placeholder: |
        Technical specification:
        
        Examples:
        ```
        // Example code
        ```
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider and why did you reject them?
      placeholder: |
        Alternative 1:
        - Pros:
        - Cons:
        - Why rejected:
    validations:
      required: true
      
  - type: dropdown
    id: impact-area
    attributes:
      label: Impact Area
      description: Which part of WEKAOU does this affect?
      options:
        - META-2.5 Core (SPOC-M, CRL, K-Cycle)
        - Tier-1 Core Patterns
        - Tier-2 Stable Frameworks
        - Tier-3 Experimental
        - Governance
        - Tooling
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change?
      description: Does this require existing implementations to change?
      options:
        - "No (backward compatible)"
        - "Yes (breaking change)"
        - "Uncertain"
    validations:
      required: true
      
  - type: textarea
    id: migration
    attributes:
      label: Migration Path
      description: If breaking change, how will existing implementations adapt?
      placeholder: |
        For implementations using X:
        1. Step 1
        2. Step 2
        
        Deprecated features will be supported until:
    validations:
      required: false
      
  - type: textarea
    id: prior-art
    attributes:
      label: Prior Art
      description: Are there similar approaches in other standards or systems?
      placeholder: |
        - Similar feature in X: [link]
        - Related work in Y: [link]
    validations:
      required: false
      
  - type: textarea
    id: unresolved
    attributes:
      label: Unresolved Questions
      description: What aspects still need community input?
      placeholder: |
        - Question 1:
        - Question 2:
    validations:
      required: false
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Proposal Checklist
      description: Confirm you've completed these steps
      options:
        - label: I have searched for existing RFCs on this topic
          required: true
        - label: I am willing to implement this change or help coordinate implementation
          required: false
        - label: I have discussed this informally in wekaou-community
          required: false
